# -*- coding: utf-8 -*-
"""Lab4Results

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1soPPh9TWyY6x_eGs72NKvKgSSbWanJEa
"""

import pandas as pd
df = pd.read_csv("air_quality_data.csv")

display(df)

import matplotlib.pyplot as plt

plt.hist(df["PM25"])
plt.ylabel("Frequency")
plt.xlabel("mg/L")
plt.show()

