# -*- coding: utf-8 -*-
"""Lab 9

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ya4xER98oDfRzx-SOHry8K6U2QtFwJ_B
"""

# Step 4

import RPi.GPIO as GPIO
import datetime

def my_callback(channel):
    if GPIO.input(channel) == GPIO.HIGH:
        print('\n▼  at ' + str(datetime.datetime.now()))
    else:
        print('\n ▲ at ' + str(datetime.datetime.now()))

try:
    GPIO.setmode(GPIO.BCM)
    GPIO.setup(6, GPIO.IN)
    GPIO.add_event_detect(6, GPIO.BOTH, callback=my_callback)

    message = raw_input('\nPress any key to exit.\n')

finally:
    GPIO.cleanup()

print("Goodbye!")